import pandas as pd

customers = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/olist_customers_dataset.csv")
geolocation = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/olist_geolocation_dataset.csv")
order_items = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/olist_order_items_dataset.csv")
payments = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/olist_order_payments_dataset.csv")
reviews = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/olist_order_reviews_dataset.csv")
orders = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/olist_orders_dataset.csv")
products = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/olist_products_dataset.csv")
sellers = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/olist_sellers_dataset.csv")
translation = pd.read_csv("D:/Projects/Sales-Business-Analytics/Data/Raw/product_category_name_translation.csv")

print("Customers")
print(customers.head())
print(customers.shape)
print(customers.columns)
customers.info()
print(customers.isnull().sum())

print("Geolocation")
print(geolocation.head())
print(geolocation.shape)
print(geolocation.columns)
geolocation.info()
print(geolocation.isnull().sum())

print("Order Items")
print(order_items.head())
print(order_items.shape)
print(order_items.columns)
order_items.info()
print(order_items.isnull().sum())

print("Payments")
print(payments.head())
print(payments.shape)
print(payments.columns)
payments.info()
print(payments.isnull().sum())

print("Reviews")
print(reviews.head())
print(reviews.shape)
print(reviews.columns)
reviews.info()
print(reviews.isnull().sum())

print("Orders")
print(orders.head())
print(orders.shape)
print(orders.columns)
orders.info()
print(orders.isnull().sum())

print("Products")
print(products.head())
print(products.shape)
print(products.columns)
products.info()
print(products.isnull().sum())

print("Sellers")
print(sellers.head())
print(sellers.shape)
print(sellers.columns)
sellers.info()
print(sellers.isnull().sum())

print("Translation")
print(translation.head())
print(translation.shape)
print(translation.columns)
translation.info()
print(translation.isnull().sum())